//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Nazwa oryginalnego pliku:
// Data generowania: 18.01.2019 17:05:48
namespace Lab1Zad
{
    
    /// <summary>
    /// Brak komentarzy dla elementu dbModel.Globalne w schemacie.
    /// </summary>
    /// <KeyProperties>
    /// Id_uzytkownika
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="dbModel", Name="Globalne")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Globalne : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Utwórz nowy obiekt Globalne.
        /// </summary>
        /// <param name="id_uzytkownika">Wartość wstępna elementu Id_uzytkownika.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Globalne CreateGlobalne(int id_uzytkownika)
        {
            Globalne globalne = new Globalne();
            globalne.Id_uzytkownika = id_uzytkownika;
            return globalne;
        }
        /// <summary>
        /// Brak komentarzy dla właściwości Id_uzytkownika w schemacie.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Id_uzytkownika
        {
            get
            {
                return this._Id_uzytkownika;
            }
            set
            {
                this.OnId_uzytkownikaChanging(value);
                this.ReportPropertyChanging("Id_uzytkownika");
                this._Id_uzytkownika = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id_uzytkownika");
                this.OnId_uzytkownikaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Id_uzytkownika;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnId_uzytkownikaChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnId_uzytkownikaChanged();
        /// <summary>
        /// Brak komentarzy dla właściwości Nazwa_Uzytkownika w schemacie.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nazwa_Uzytkownika
        {
            get
            {
                return this._Nazwa_Uzytkownika;
            }
            set
            {
                this.OnNazwa_UzytkownikaChanging(value);
                this.ReportPropertyChanging("Nazwa_Uzytkownika");
                this._Nazwa_Uzytkownika = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Nazwa_Uzytkownika");
                this.OnNazwa_UzytkownikaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nazwa_Uzytkownika;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNazwa_UzytkownikaChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNazwa_UzytkownikaChanged();
        /// <summary>
        /// Brak komentarzy dla właściwości Data_Uruchomienia w schemacie.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Data_Uruchomienia
        {
            get
            {
                return this._Data_Uruchomienia;
            }
            set
            {
                this.OnData_UruchomieniaChanging(value);
                this.ReportPropertyChanging("Data_Uruchomienia");
                this._Data_Uruchomienia = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Data_Uruchomienia");
                this.OnData_UruchomieniaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Data_Uruchomienia;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnData_UruchomieniaChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnData_UruchomieniaChanged();
        /// <summary>
        /// Brak komentarzy dla właściwości Godzina_Uruchomienia w schemacie.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Godzina_Uruchomienia
        {
            get
            {
                return this._Godzina_Uruchomienia;
            }
            set
            {
                this.OnGodzina_UruchomieniaChanging(value);
                this.ReportPropertyChanging("Godzina_Uruchomienia");
                this._Godzina_Uruchomienia = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Godzina_Uruchomienia");
                this.OnGodzina_UruchomieniaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Godzina_Uruchomienia;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGodzina_UruchomieniaChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGodzina_UruchomieniaChanged();
        /// <summary>
        /// Brak komentarzy dla właściwości Ilu_uzytkownikow w schemacie.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> Ilu_uzytkownikow
        {
            get
            {
                return this._Ilu_uzytkownikow;
            }
            set
            {
                this.OnIlu_uzytkownikowChanging(value);
                this.ReportPropertyChanging("Ilu_uzytkownikow");
                this._Ilu_uzytkownikow = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Ilu_uzytkownikow");
                this.OnIlu_uzytkownikowChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _Ilu_uzytkownikow;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIlu_uzytkownikowChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIlu_uzytkownikowChanged();
        /// <summary>
        /// Brak komentarzy dla właściwości czy_aktywny w schemacie.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string czy_aktywny
        {
            get
            {
                return this._czy_aktywny;
            }
            set
            {
                this.Onczy_aktywnyChanging(value);
                this.ReportPropertyChanging("czy_aktywny");
                this._czy_aktywny = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("czy_aktywny");
                this.Onczy_aktywnyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _czy_aktywny;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onczy_aktywnyChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onczy_aktywnyChanged();
        /// <summary>
        /// Brak komentarzy dla właściwości ile_razy_uruchomil w schemacie.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> ile_razy_uruchomil
        {
            get
            {
                return this._ile_razy_uruchomil;
            }
            set
            {
                this.Onile_razy_uruchomilChanging(value);
                this.ReportPropertyChanging("ile_razy_uruchomil");
                this._ile_razy_uruchomil = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ile_razy_uruchomil");
                this.Onile_razy_uruchomilChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _ile_razy_uruchomil;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onile_razy_uruchomilChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onile_razy_uruchomilChanged();
        /// <summary>
        /// Brak komentarzy dla właściwości klikniecia_przycisk w schemacie.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> klikniecia_przycisk
        {
            get
            {
                return this._klikniecia_przycisk;
            }
            set
            {
                this.Onklikniecia_przyciskChanging(value);
                this.ReportPropertyChanging("klikniecia_przycisk");
                this._klikniecia_przycisk = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("klikniecia_przycisk");
                this.Onklikniecia_przyciskChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _klikniecia_przycisk;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onklikniecia_przyciskChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onklikniecia_przyciskChanged();
        /// <summary>
        /// Brak komentarzy dla właściwości klikniecia_obraz w schemacie.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> klikniecia_obraz
        {
            get
            {
                return this._klikniecia_obraz;
            }
            set
            {
                this.Onklikniecia_obrazChanging(value);
                this.ReportPropertyChanging("klikniecia_obraz");
                this._klikniecia_obraz = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("klikniecia_obraz");
                this.Onklikniecia_obrazChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _klikniecia_obraz;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onklikniecia_obrazChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onklikniecia_obrazChanged();
        /// <summary>
        /// Brak komentarzy dla właściwości ilu_zarejestrowanych w schemacie.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> ilu_zarejestrowanych
        {
            get
            {
                return this._ilu_zarejestrowanych;
            }
            set
            {
                this.Onilu_zarejestrowanychChanging(value);
                this.ReportPropertyChanging("ilu_zarejestrowanych");
                this._ilu_zarejestrowanych = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ilu_zarejestrowanych");
                this.Onilu_zarejestrowanychChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _ilu_zarejestrowanych;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onilu_zarejestrowanychChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onilu_zarejestrowanychChanged();
        /// <summary>
        /// Brak komentarzy dla właściwości numer_okna w schemacie.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> numer_okna
        {
            get
            {
                return this._numer_okna;
            }
            set
            {
                this.Onnumer_oknaChanging(value);
                this.ReportPropertyChanging("numer_okna");
                this._numer_okna = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("numer_okna");
                this.Onnumer_oknaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _numer_okna;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onnumer_oknaChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onnumer_oknaChanged();
        /// <summary>
        /// Brak komentarzy dla właściwości iterator w schemacie.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> iterator
        {
            get
            {
                return this._iterator;
            }
            set
            {
                this.OniteratorChanging(value);
                this.ReportPropertyChanging("iterator");
                this._iterator = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("iterator");
                this.OniteratorChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _iterator;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OniteratorChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OniteratorChanged();
        /// <summary>
        /// Brak komentarzy dla właściwości Id_sesji w schemacie.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Id_sesji
        {
            get
            {
                return this._Id_sesji;
            }
            set
            {
                this.OnId_sesjiChanging(value);
                this.ReportPropertyChanging("Id_sesji");
                this._Id_sesji = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Id_sesji");
                this.OnId_sesjiChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Id_sesji;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnId_sesjiChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnId_sesjiChanged();
    }
    /// <summary>
    /// Brak komentarzy dla elementu dbEntities w schemacie.
    /// </summary>
    public partial class dbEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Inicjuje nowy obiekt dbEntities, używając parametrów połączenia znalezionych w sekcji „dbEntities” pliku konfiguracyjnego aplikacji.
        /// </summary>
        public dbEntities() : 
                base("name=dbEntities", "dbEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Zainicjuj nowy obiekt dbEntities.
        /// </summary>
        public dbEntities(string connectionString) : 
                base(connectionString, "dbEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Zainicjuj nowy obiekt dbEntities.
        /// </summary>
        public dbEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "dbEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Brak komentarzy dla elementu Globalne w schemacie.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Globalne> Globalne
        {
            get
            {
                if ((this._Globalne == null))
                {
                    this._Globalne = base.CreateQuery<Globalne>("[Globalne]");
                }
                return this._Globalne;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Globalne> _Globalne;
        /// <summary>
        /// Brak komentarzy dla elementu Globalne w schemacie.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToGlobalne(Globalne globalne)
        {
            base.AddObject("Globalne", globalne);
        }
    }
}
